services:
  - type: web
    name: passport-management-frontend
    env: static
    buildCommand: npm install && TSC_COMPILE_ON_ERROR=true npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 